config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  devise_for :participants, controllers: { sessions: 'participants/sessions' }

  resources :rooms, only: [:new, :create, :show, :index]

  scope :my do
    #
  end

  root to: 'root#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/joined_room.rb
class JoinedRoom < ApplicationRecord

  belongs_to :room
  belongs_to :participant

  has_many :messages, dependent: :destroy

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :joined_room
  belongs_to :participant, foreign_key: :posted_by_id

  validates :content, presence: true

end

app/models/participant.rb
class Participant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :owned_rooms, class_name: "Room", dependent: :destroy

  has_many :joined_rooms, -> { where(joined: true) }, class_name: "JoinedRoom", foreign_key: :participant_id
  has_many :rooms, through: :joined_rooms, source: :room

  has_many :messages, foreign_key: :posted_by_id

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true

  with_options unless: proc { |p| p.password.blank? } do
    validates :password, presence: true, length: { minimum: 6 }, confirmation: true
    validates :password_confirmation, presence: true, length: { minimum: 6 }
  end

  def join room_id
    room = Room.find_by id: room_id
    unless room.blank?
      joined_room = joined_rooms.find_by room_id: room_id
      if joined_room.blank?
        rooms << room
      else
        joined_room.update_attributes! joined: true
      end
    end
  end

  def leave room_id
    room = joined_rooms.find_by room_id: room_id
    room.update_attributes!(joined: false) unless room.blank?
  end

  def joined? room
    self.in?(room.participants) unless room.blank?
  end

  def left? room
    !joined?(room) unless room.blank?
  end

end

app/models/room.rb
class Room < ApplicationRecord

  after_save :join_owned_room

  belongs_to :owner, class_name: "Participant", foreign_key: :participant_id

  has_many :joined_participants, -> { where(joined: true) }, class_name: "JoinedRoom", foreign_key: :room_id, dependent: :destroy
  has_many :participants, through: :joined_participants, source: :participant

  has_many :joined_rooms, -> { where(joined: true) }, class_name: "JoinedRoom", foreign_key: :room_id, dependent: :destroy
  has_many :messages, through: :joined_rooms, source: :messages

  def add participant_id
    participant = Participant.find_by id: participant_id
    unless participant.blank?
      joined_participant = joined_participants.find_by participant_id: participant_id
      if joined_participant.blank?
        participants << participant
      else
        joined_participant.update_attributes! joined: true
      end
    end
  end

  def remove participant_id
    participant = joined_participants.find_by participant_id: participant_id
    participant.update_attributes!(joined: false) unless participant.blank?
  end

  def added? participant
    participant.joined?(self) unless participant.blank?
  end

  def removed? participant
    participant.left?(self) unless participant.blank?
  end

private

  def join_owned_room
    add owner.id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :authenticate_participant!

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

end

app/controllers/my_controller.rb
class MyController < ApplicationController

  before_action :owned_rooms

  def index

  end

  def new
    @room = Room.new
  end

  def create
    @room = current_participant.rooms.build(room_params)
    if @room.save
      flash[:success] = 'Chat room added!'
      redirect_to rooms_path
    else
      render 'new'
    end
  end

  def show
    @room = Room.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

private

  def owned_rooms
    @rooms = current_participant.owned_rooms
  end

  def room_params
    params.require(:room).permit(:title)
  end

end

app/controllers/participants/sessions_controller.rb
class Participants::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all

    render action: 'index.html.haml'
  end

  def new
    @room = Room.new

    respond_to{ |f| f.html }
  end

  def create
    @room = current_participant.owned_rooms.build(room_params)
    if @room.save
      flash[:success] = 'Chat room added!'
      redirect_to rooms_path
    else
      render 'new'
    end

    respond_to{ |f| f.html }
  end

  def show
    @room = Room.includes(:messages).find_by(id: params[:id])
    @message = Message.new

    respond_to{ |f| f.html }
  end

private

  def room_params
    params.require(:room).permit(:title)
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def index
    path = rooms_path unless current_participant.blank?

    redirect_to path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for participant, opts = {}
    opts[:alt] = participant.name
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(participant.email)}?s=#{opts.delete(:size) { 40 }}", opts
  end

  def class_for flash_type
    { success: 'success', error: 'danger', warning: 'warning', alert: 'danger',
      notice: 'info', default: 'primary', notice_default: 'muted' }[flash_type.to_sym] || flash_type.to_s
  end

  def icon_for flash_type
    { success: 'check-circle-o', error: 'exclamation-circle', danger: 'ban', alert: 'exclamation-circle',
     notice: 'info-circle', notice_default: 'info-circle' }[flash_type.to_sym] || 'info-circle'
  end

  def flash_messages opts = {}
    render partial: 'layouts/flash_messages'
  end

end

app/views/layouts/_flash_messages.html.haml
- flash.to_h.dup.each do |msg_type, message|
  .alert{ class: "alert-#{class_for(msg_type)}", id: "flash-#{msg_type}", 'data-closable': true }
    %button.close{ 'aria-label': 'Close', 'data-dismiss': :alert }
      %span{ 'aria-hidden': :true } &times;
    %i.icon{ class: "fa fa-#{icon_for(msg_type)}" }
    = message.to_s.html_safe
- flash.clear

app/views/layouts/application.html.haml
- title = content_for?(:title) ? yield(:title) : 'Chat Room'
!!!
%html
  %head
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv': 'Content-Type' }/
    %title= title
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{ src: 'https://use.fontawesome.com/09b979ea9c.js' }
  %body{ class: "#{ participant_signed_in? ? 'cover-body' : 'sign-in' }" }
    #flash-block= flash_messages
    - if participant_signed_in?
      .site-wrapper
        .site-wrapper-inner
          .cover-container
            .masthead.clearfix
              .inner
                %h3.masthead-brand
                  %a.nav-link{ href: root_path }
                    %i.icon.fa.fa-home
                %nav.nav.nav-masthead
                  %a.nav-link{ href: root_path, class: "#{request.path == root_path ? 'active' : false}" } My Rooms
                  %a.nav-link{ href: rooms_path, class: "#{request.path == rooms_path ? 'active' : false}" } Chat Rooms
                  %a.nav-link{ href: destroy_participant_session_path, 'data-method': :delete } Sign Out
            .inner.cover
              = yield
            .mastfoot
              .inner
                %p
                  %a{ href: 'http://gitlab.com/marlox' } @marlox
    - else
      = yield

app/views/messages/_message.html.haml
.card
  .card-block
    .row
      .col-md-1
        = gravatar_for message.user
      .col-md-11
        %p.card-text
          %span.text-muted
            = message.user.name
            at #{message.timestamp} says
          %br/
          = message.body

app/views/rooms/_room.html.haml
%li= link_to "Enter #{chat_room.name}", room_path(room)

app/views/rooms/index.html.haml
%h1 Chat Rooms
%p.lead= link_to 'New chat room', new_room_path, class: 'btn btn-primary'
%ul
  = render @rooms

app/views/rooms/new.html.haml
%h1 Add chat room
= form_for @room do |f|
  .form-group
    = f.label :name
    = f.text_field :name, autofocus: true, class: 'form-control'
    = f.label :topic
    = f.text_area :topic, class: 'form-control'
  = f.submit 'Add!', class: 'btn btn-primary'

app/views/rooms/show.html.haml
%h1= @room.name
%legend= @room.topic
#messages{"data-room-id" => "#{@room.id}"}
  = render @room.messages
%hr/
= form_for @message, url: '#' do |f|
  = hidden_field_tag 'joined_room_id', @room.id
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
    -#%small.text-muted From 2 to 1000 characters
  = f.submit 'Post', class: 'btn btn-primary btn-lg'